from flask import Flask, render_template, request
import requests

app = Flask(__name__)

@app.route('/')
def index():
    return render_template('index.html')

''' That's a piece of data that out code is retriving from the API
 {
    "id": "bitcoin",
    "symbol": "btc",
    "name": "Bitcoin",
    "platforms": {}
  }, '''

@app.route('/get_data', methods=['POST'])
def get_data():
    crypto = request.form['crypto']
    API_KEY = 'CG-RZ8d5jQuPXgFEMbnDEdewufu' 
    url = 'https://api.coingecko.com/api/v3/simple/price'
    params = {
        'ids': crypto,
        'vs_currencies': 'usd'
    }
    headers = {
        'Authorization': f'Bearer {API_KEY}'
    }
    response = requests.get(url, params=params, headers=headers)
    data = response.json()
    price = data[crypto]['usd']
    return render_template('result.html', crypto=crypto, price=price)

# That's the address generated by our code:
# https://api.coingecko.com/api/v3/simple/price?ids=bitcoin&vs_currencies=usd

@app.route('/bitcoin_event')
def bitcoin_event():
    return render_template('bitcoin_event.html')

if __name__ == '__main__':
    app.run(debug=True)
